#!/bin/bash

#DEBHELPER#

# postrm script for cryptsetup-modified-functions

#set -e

case "$1" in
  purge|remove) dpkg-divert --quiet                                               \
                            --remove                                              \
                            --package mx-system              \
                            --rename                                              \
                            --divert /usr/lib/os-release.distrib \
                            /usr/lib/os-release
                ;;

             *) :
                ;;
esac 

exit 0
