#!/bin/bash

#DEBHELPER#

# postrm script for mx-system

#set -e

case "$1" in
  purge|remove)
    for F in \
        /usr/share/applications/conky.desktop       \
        /usr/share/themes/Clearlooks/gtk-2.0/gtkrc  \
        /usr/share/themes/Crux/gtk-2.0/gtkrc        \
        /usr/share/themes/Industrial/gtk-2.0/gtkrc  \
        /usr/share/themes/Mist/gtk-2.0/gtkrc        \
        /usr/share/themes/Redmond/gtk-2.0/gtkrc     \
        /usr/share/themes/ThinIce/gtk-2.0/gtkrc     \
        /usr/lib/linux-boot-probes/mounted/40grub2 \
        /usr/share/applications/alsamixer.desktop \
        /usr/share/applications/nano.desktop \
        /usr/share/applications/display-im7.q16.desktop \
        /usr/sbin/dkms
        /usr/lib/shim/BOOTX64.CSV
    do
        dpkg-divert --quiet --package mx-system --rename \
                    --divert $F.dpkg-dist --remove $F || :
    done
  ;;
  *) :
  ;;

esac

exit 0
