#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
    	
	## update icon file for luckybackup, if installed
    if [ -e "/usr/share/icons/hicolor/scalable/apps/luckybackup.svg" ]; then
		rm /usr/share/icons/hicolor/scalable/apps/luckybackup.svg
	fi
	
	# update icons for ndisgtk
	if [ -e "/usr/share/icons/hicolor/48x48/apps/ndisgtk.png" ]; then
		rm /usr/share/icons/hicolor/48x48/apps/ndisgtk.png
	fi
	if [ -e "/usr/share/icons/hicolor/48x48/apps/ndisgtk.svg" ]; then
		rm /usr/share/icons/hicolor/48x48/apps/ndisgtk.svg
	fi
	if [ -e "/usr/share/icons/hicolor/scalable/apps/ndisgtk.svg" ]; then
		rm /usr/share/icons/hicolor/scalable/apps/ndisgtk.svg
	fi
	
	#remove bogus synaptic-kde.desktop file
	if [ -e "/usr/share/applications/synaptic-kde.desktop" ]; then
		rm /usr/share/applications/synaptic-kde.desktop
	fi

fi

#dpkg-diver some apps that don't have desktop files and a few that need hidden
case "$1" in
  install|upgrade) dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package mx-system              \
                               --rename                                              \
                               --divert /usr/share/applications/conky.desktop.dpkg-dist \
                               /usr/share/applications/conky.desktop || :
                               
              	   dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package mx-system              \
                               --rename                                              \
                               --divert /usr/share/applications/alsamixer.desktop.dpkg-dist \
                               /usr/share/applications/alsamixer.desktop || :
                               
				   dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package mx-system              \
                               --rename                                              \
                               --divert /usr/share/applications/display-im7.q16.desktop.dpkg-dist \
                               /usr/share/applications/display-im7.q16.desktop || :
                               
				   dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package mx-system              \
                               --rename                                              \
                               --divert /usr/share/applications/nano.desktop.dpkg-dist \
                               /usr/share/applications/nano.desktop || :
#divert os-prober to a fixed version
                   dpkg-divert --quiet --package mx-system --rename \
                      --divert /usr/lib/linux-boot-probes/mounted/40grub2.dpkg-dist \
                      --add    /usr/lib/linux-boot-probes/mounted/40grub2 || :

#remove old dkms.mx divert, if it exists
					if [ -x /usr/sbin/dkms.mx ]; then
					#remove mx-system version file because both can't exist
						rm -f /usr/sbin/dkms
						# remove divert, /usr/sbin/dkms should be debian's version
        				dpkg-divert --package mx-system --rename \
                   		--divert /usr/sbin/dkms.dpkg-dist --remove /usr/sbin/dkms || :
					fi

#divert dkms to a so a wrapper can be used
                   dpkg-divert --quiet --package mx-system --rename \
                      --divert /usr/sbin/dkms.real \
                      --add    /usr/sbin/dkms || :
                    if [ ! -x /usr/sbin/dkms.real ]; then
                    #copy new file, because the divert below doesn't quite do it 
                    #without reinstalling dkms.
                   		cp /usr/sbin/dkms /usr/sbin/dkms.real
                   	fi
                    
                      
#MX descriptor for BOOTX64.CSV                     
                   dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package mx-system              \
                               --rename                                              \
                               --divert /usr/lib/shim/BOOTX64.CSV.dpkg-dist \
                               /usr/lib/shim/BOOTX64.CSV || :

                   ;;
                   

                *) :
                   ;;
esac 

#DEBHELPER#
